# Github Project Workflow
# This wf will move project issues 
# GPT was partially used for this
name: Branch-Issue-Link Workflow

on:
  push:
    branches:
      - '*'

jobs:
  check_issue_link:
    runs-on: ubuntu-latest

    steps:
    - name: Check for Issue Link
      id: check_link
      run: |
        branch_name=$(git branch --show-current)
        if [[ $branch_name =~ ^issue-([0-9]+)$ ]]; then 
          echo "Branch is linked to an issue."
          issue_number="${BASH_REMATCH[1]}"
          echo "Issue number: $issue_number"

          # Use GitHub API to move the issue to another column
          curl -X POST \
            -H "Authorization: token ${{ secrets.AA_TOKEN }}" \
            -H "Accept: application/vnd.github.inertia-preview+json" \
            https://api.github.com/projects/columns/🏗 In progress/moves \
            -d '{"position": "bottom", "issue_id": '$issue_number'}'
        else
          echo "Branch is not linked to an issue."
        fi
