name: Release executables on tag

on:
  push:
    branches:
      -main
    tags:
      - "v*.*.*"

jobs:     
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set Up .NET 7
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
  
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "Chirp-v*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
